### ISSUE TITLE
Bing Chat is now a microsoft-edge link

### ISSUE THREAD

**Issue by thepwrtank18** [IKavanagh/BingChatInFirefox#3]
![image](https://github.com/IKavanagh/BingChatInFirefox/assets/57580668/fea5bdc9-88bc-47f8-a0de-dd55d68788a1)
https://www.microsoft.com/en-us/edge/launch/bing-chat-paywall?form=QBLH&q=bing%20ai&ch

**Comment by IKavanagh** [comment]
Navigating to [chat.bing.com](http://bing.chat.com) still works for me but I don't think it will work indefinitely if Microsoft really do want to block access.
